worker_processes 1;
error_log /dev/null;
pid /app/.nginx/nginx.pid;

events {
    worker_connections 128;
}

http {
    server_tokens off;
    access_log /dev/null;

    client_body_temp_path /app/.nginx/tmp/client_body;
    proxy_temp_path /app/.nginx/tmp/proxy;

    ${LIMIT_REQ_ZONE}

    client_body_timeout 5s;
    client_header_timeout 5s;
    send_timeout 5s;

    upstream ${UPSTREAM} {
        server 127.0.0.1:${BACKEND_PORT};
    }

    server {
        listen ${PORT} ssl default_server;
        server_name _;

        ssl_certificate /app/certs/cert.pem;
        ssl_certificate_key /app/certs/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 10m;
        ssl_session_tickets off;

        proxy_connect_timeout 5s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;

        location ${LOCATION} {
            ${LIMIT_REQ}
            limit_except GET POST {
                deny all;
            }
            proxy_pass http://${UPSTREAM};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
        }

        ${EXTRA_LOCATION}
    }
}
